### ISSUE TITLE
Got Import Failed 

### ISSUE THREAD

**Issue by PGCRT** [Lightricks/ComfyUI-LTXVideo#2]
On the ComfyUI teminal

```
Traceback (most recent call last):
  File "D:\SD\Nouveau dossier\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2026, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\SD\Nouveau dossier\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LexTools\__init__.py", line 2, in <module>
    from .nodes import SegformerNode,ImageCaptioningNode,ImageProcessingNode
  File "D:\SD\Nouveau dossier\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LexTools\nodes\ImageProcessingNode.py", line 2, in <module>
    from fastapi import FastApi
ImportError: cannot import name 'FastApi' from 'fastapi' (D:\SD\Nouveau dossier\ComfyUI_windows_portable\python_embeded\Lib\site-packages\fastapi\__init__.py). Did you mean: 'FastAPI'?

Cannot import D:\SD\Nouveau dossier\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LexTools module for custom nodes: cannot import name 'FastApi' from 'fastapi' (D:\SD\Nouveau dossier\ComfyUI_windows_portable\python_embeded\Lib\site-packages\fastapi\__init__.py)
Please install pyav to use video processing functions.
Initializing EasyNodes. Auto-registration: True
Traceback (most recent call last):
  File "D:\SD\Nouveau dossier\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2026, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\SD\Nouveau dossier\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo\__init__.py", line 3, in <module>
    from .transformer import LTXVModelConfigurator, LTXVShiftSigmas
  File "D:\SD\Nouveau dossier\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo\transformer.py", line 15, in <module>
    from ltx_video.models.transformers.transformer3d import Transformer3DModel
ModuleNotFoundError: No module named 'ltx_video'

Cannot import D:\SD\Nouveau dossier\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo module for custom nodes: No module named 'ltx_video'
```

When manually installing requirements

```
(base) D:\SD\Nouveau dossier\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo>pip install -r requirements.txt
Collecting ltx-video@ git+https://github.com/Lightricks/LTX-Video.git@ltx-video-0.9 (from -r requirements.txt (line 2))
  Cloning https://github.com/Lightricks/LTX-Video.git (to revision ltx-video-0.9) to c:\users\pgc\appdata\local\temp\pip-install-ztxoh6c8\ltx-video_4e26cbcdd8e0435d8201594e6b235f95
  Running command git clone --filter=blob:none --quiet https://github.com/Lightricks/LTX-Video.git 'C:\Users\PGC\AppData\Local\Temp\pip-install-ztxoh6c8\ltx-video_4e26cbcdd8e0435d8201594e6b235f95'
  Running command git checkout -q 48a9500f50da637ba39bfb9e318ce938e589beca
  Resolved https://github.com/Lightricks/LTX-Video.git to commit 48a9500f50da637ba39bfb9e318ce938e589beca
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting comfyui-easynodes (from -r requirements.txt (line 1))
  Using cached ComfyUI_EasyNodes-1.2.7-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: huggingface_hub==0.25.2 in c:\users\pgc\anaconda3\lib\site-packages (from -r requirements.txt (line 3)) (0.25.2)
Requirement already satisfied: filelock in c:\users\pgc\anaconda3\lib\site-packages (from huggingface_hub==0.25.2->-r requirements.txt (line 3)) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\pgc\anaconda3\lib\site-packages (from huggingface_hub==0.25.2->-r requirements.txt (line 3)) (2024.6.1)
Requirement already satisfied: packaging>=20.9 in c:\users\pgc\anaconda3\lib\site-packages (from huggingface_hub==0.25.2->-r requirements.txt (line 3)) (24.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\pgc\anaconda3\lib\site-packages (from huggingface_hub==0.25.2->-r requirements.txt (line 3)) (6.0.1)
Requirement already satisfied: requests in c:\users\pgc\anaconda3\lib\site-packages (from huggingface_hub==0.25.2->-r requirements.txt (line 3)) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\pgc\anaconda3\lib\site-packages (from huggingface_hub==0.25.2->-r requirements.txt (line 3)) (4.66.5)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\pgc\anaconda3\lib\site-packages (from huggingface_hub==0.25.2->-r requirements.txt (line 3)) (4.11.0)
Requirement already satisfied: torch in c:\users\pgc\anaconda3\lib\site-packages (from comfyui-easynodes->-r requirements.txt (line 1)) (2.5.1)
Requirement already satisfied: pillow in c:\users\pgc\anaconda3\lib\site-packages (from comfyui-easynodes->-r requirements.txt (line 1)) (10.4.0)
Collecting ansi2html (from comfyui-easynodes->-r requirements.txt (line 1))
  Using cached ansi2html-1.9.2-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: colorama in c:\users\pgc\anaconda3\lib\site-packages (from comfyui-easynodes->-r requirements.txt (line 1)) (0.4.6)
Collecting coloredlogs (from comfyui-easynodes->-r requirements.txt (line 1))
  Using cached coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: numpy in c:\users\pgc\anaconda3\lib\site-packages (from comfyui-easynodes->-r requirements.txt (line 1)) (1.26.4)
Collecting openai (from comfyui-easynodes->-r requirements.txt (line 1))
  Using cached openai-1.55.0-py3-none-any.whl.metadata (24 kB)
Collecting diffusers~=0.28.2 (from ltx-video@ git+https://github.com/Lightricks/LTX-Video.git@ltx-video-0.9->-r requirements.txt (line 2))
  Using cached diffusers-0.28.2-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: transformers~=4.44.2 in c:\users\pgc\anaconda3\lib\site-packages (from ltx-video@ git+https://github.com/Lightricks/LTX-Video.git@ltx-video-0.9->-r requirements.txt (line 2)) (4.44.2)
Collecting sentencepiece~=0.1.96 (from ltx-video@ git+https://github.com/Lightricks/LTX-Video.git@ltx-video-0.9->-r requirements.txt (line 2))
  Using cached sentencepiece-0.1.99.tar.gz (2.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\PGC\AppData\Local\Temp\pip-install-ztxoh6c8\sentencepiece_3a60a4b5b2764dffaca410dff38b06e1\setup.py", line 126, in <module>
          subprocess.check_call([
        File "C:\Users\PGC\anaconda3\Lib\subprocess.py", line 408, in check_call
          retcode = call(*popenargs, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\PGC\anaconda3\Lib\subprocess.py", line 389, in call
          with Popen(*popenargs, **kwargs) as p:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\PGC\anaconda3\Lib\subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\PGC\anaconda3\Lib\subprocess.py", line 1538, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by BoosterCore** [comment]
same here

**Comment by al3dv2** [comment]
Same

**Comment by jpgallegoar** [comment]
I didn't get this. I'm using it currently. I cloned it into custom nodes, did pip install -r requirements.txt in this folder and it worked. I did start from a fresh ComfyUI though

**Comment by PGCRT** [comment]
> I didn't get this. I'm using it currently. I cloned it into custom nodes, did pip install -r requirements.txt in this folder and it worked. I did start from a fresh ComfyUI though

May I ask what version of sentencepiece do you use? "pip show sentencepiece"

**Comment by jpgallegoar** [comment]
> > I didn't get this. I'm using it currently. I cloned it into custom nodes, did pip install -r requirements.txt in this folder and it worked. I did start from a fresh ComfyUI though
> 
> May I ask what version of sentencepiece do you use? "pip show sentencepiece"

Version: 0.1.99

I did have issues installing it in python 3.11 so I went with the 3.10.5 suggested in the official repo

**Comment by jpgallegoar** [comment]
> I have SentencePiece 0.2.0 with Python 3.12.7. I think I'm giving up on this, but thank you for your answers

just create a conda env with python 3.10.5

**Comment by sanguivore-easyco** [comment]
> > I have SentencePiece 0.2.0 with Python 3.12.7. I think I'm giving up on this, but thank you for your answers
> 
> just create a conda env with python 3.10.5

I'm on 3.10.12 (with some other custom nodes requiring that).

Here's the relevant output when installing the broken dep via pip
```
Collecting ltx-video@ git+https://github.com/Lightricks/LTX-Video.git@ltx-video-0.9
  Cloning https://github.com/Lightricks/LTX-Video.git (to revision ltx-video-0.9) to /tmp/pip-install-g1649iyf/ltx-video_e68b4148616e4e2dab8b36f512c56241
  Running command git clone --filter=blob:none --quiet https://github.com/Lightricks/LTX-Video.git /tmp/pip-install-g1649iyf/ltx-video_e68b4148616e4e2dab8b36f512c56241
  Running command git checkout -q 48a9500f50da637ba39bfb9e318ce938e589beca
  Resolved https://github.com/Lightricks/LTX-Video.git to commit 48a9500f50da637ba39bfb9e318ce938e589beca
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Generating metadata for package ltx-video produced metadata for project name unknown. Fix your #egg=ltx-video fragments.
Discarding git+https://github.com/Lightricks/LTX-Video.git@ltx-video-0.9: Requested unknown from git+https://github.com/Lightricks/LTX-Video.git@ltx-video-0.9 has inconsistent name: filename has 'ltx-video', but metadata has 'unknown'
ERROR: Could not find a version that satisfies the requirement ltx-video (unavailable) (from versions: none)
ERROR: No matching distribution found for ltx-video (unavailable)
```

**Comment by jpgallegoar** [comment]
> > > I have SentencePiece 0.2.0 with Python 3.12.7. I think I'm giving up on this, but thank you for your answers
> > 
> > 
> > just create a conda env with python 3.10.5
> 
> I'm on 3.10.12 (with some other custom nodes requiring that).
> 
> Here's the relevant output when installing the broken dep via pip
> 
> ```
> Collecting ltx-video@ git+https://github.com/Lightricks/LTX-Video.git@ltx-video-0.9
>   Cloning https://github.com/Lightricks/LTX-Video.git (to revision ltx-video-0.9) to /tmp/pip-install-g1649iyf/ltx-video_e68b4148616e4e2dab8b36f512c56241
>   Running command git clone --filter=blob:none --quiet https://github.com/Lightricks/LTX-Video.git /tmp/pip-install-g1649iyf/ltx-video_e68b4148616e4e2dab8b36f512c56241
>   Running command git checkout -q 48a9500f50da637ba39bfb9e318ce938e589beca
>   Resolved https://github.com/Lightricks/LTX-Video.git to commit 48a9500f50da637ba39bfb9e318ce938e589beca
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Preparing metadata (pyproject.toml) ... done
>   WARNING: Generating metadata for package ltx-video produced metadata for project name unknown. Fix your #egg=ltx-video fragments.
> Discarding git+https://github.com/Lightricks/LTX-Video.git@ltx-video-0.9: Requested unknown from git+https://github.com/Lightricks/LTX-Video.git@ltx-video-0.9 has inconsistent name: filename has 'ltx-video', but metadata has 'unknown'
> ERROR: Could not find a version that satisfies the requirement ltx-video (unavailable) (from versions: none)
> ERROR: No matching distribution found for ltx-video (unavailable)
> ```

you don't need to install via pip, where did you read that? just clone the node and pip install -r requirements.txt

**Comment by sanguivore-easyco** [comment]
> Generating metadata for package ltx-video produced metadata for project name unknown. Fix your #egg

That was the dependency in `requirements.txt` that failed to install, so to clean up the log for pasting here, I ran the command to install just it.

**Comment by kvochko** [comment]
@PGCRT this should be fixed now, please let us know if you have any problems.

**Comment by PGCRT** [comment]
Yes, I reinstalled the package without issues, well played
