### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by kitmu** [Lightricks/ComfyUI-LTXVideo#20]
Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "C:\Program Files\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Program Files\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\ComfyUI\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\ComfyUI\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\ComfyUI\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "C:\Program Files\ComfyUI\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Program Files\ComfyUI\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 126, in <module>
        File "subprocess.py", line 408, in check_call
        File "subprocess.py", line 389, in call
        File "subprocess.py", line 1026, in __init__
        File "subprocess.py", line 1538, in _execute_child
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Musigreg** [comment]
Don't take my words as the solution, but I've seen many errors in many projects getting due to a "Space" is the path name. "Program files" may be an issue, since the error says "FileNotFoundError: [WinError 2] The system cannot find the file specified".

Could be something completely different, but I would try that before going further.

**Comment by kitmu** [comment]
I installed directly in the python folder after also installing Visual C++ Build Tools ("Optional" components, MSVC C++ x64/x86 build tools (this is required) and Windows 10/11 SDK (latest version is  fine)) and it worked so not sure if it was the space in the folder or that I needed to have the MSBuildtools.  Still it was obviously my prob so closing it. Leaving it in case someone else has this prob.
