### ISSUE TITLE
KeyError : 'text-encoders' - The nodes can't be loaded

### ISSUE THREAD

**Issue by neopiccolorat** [Lightricks/ComfyUI-LTXVideo#22]
Hi, 

I have this error. Is it a problem with the installation? I removed it and re-installed it multiple times.
Or is it a bug of the node?

I have the model in the checkpoints folder, and the text encoder in the "text_encoders" folder.

`FETCH DATA from: A:\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[ERROR] An error occurred while retrieving information for the 'LTXVCLIPModelLoader' node.
Traceback (most recent call last):
  File "A:\ComfyUI\server.py", line 486, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "A:\ComfyUI\server.py", line 454, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\ComfyUI\custom_nodes\ComfyUI-LTXVideo\t5_encoder.py", line 122, in INPUT_TYPES
    folder_paths.get_filename_list("text_encoders"),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\ComfyUI\folder_paths.py", line 242, in get_filename_list
    out = get_filename_list_(folder_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\ComfyUI\folder_paths.py", line 207, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
              ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'text_encoders'`

**Comment by Grownz** [comment]
Until fixed, use the ComfyUI built-in nodes with these workflows: https://comfyanonymous.github.io/ComfyUI_examples/ltxv/

**Comment by neopiccolorat** [comment]
I get this error with the workflow from the webpage :

![image](https://github.com/user-attachments/assets/d0726afe-0755-440c-9290-7d3ab9af67dc)

**Comment by Grownz** [comment]
What's your ComfyUI-Version? v0.3.4 is the current one, that has the native LTXV-nodes built in.

**Comment by kvochko** [comment]
> `KeyError: 'text_encoders'`

This key is a built-in on the latest comfy version, could you please update ComfyUI and try again?

**Comment by neopiccolorat** [comment]
I maybe found the problem.
I always had this error when using "update_comfyui.bat" in the "update" folder :

`stashing current changes
nothing to stash
creating backup branch: backup_branch_2024-11-24_15_23_50
checking out master branch
pulling latest changes
Traceback (most recent call last):
  File "A:\Stable Diffusion\ComfyUI\update\update.py", line 76, in <module>
    pull(repo)
  File "A:\Stable Diffusion\ComfyUI\update\update.py", line 19, in pull
    repo.checkout_tree(repo.get(remote_master_id))
  File "A:\Stable Diffusion\ComfyUI\python_embeded\Lib\site-packages\pygit2\repository.py", line 286, in checkout_tree
    payload.check_error(err)
  File "A:\Stable Diffusion\ComfyUI\python_embeded\Lib\site-packages\pygit2\callbacks.py", line 99, in check_error
    check_error(error_code)
  File "A:\Stable Diffusion\ComfyUI\python_embeded\Lib\site-packages\pygit2\errors.py", line 66, in check_error
    raise GitError(message)
_pygit2.GitError: 2 conflicts prevent checkout`

but since I never had any major problems, I assumed that it sill updated. And I have the new UI so.

But I just looked at the log :

`### Loading: ComfyUI-Manager (V2.51.9)
### ComfyUI Revision: 2642 [d043997d] | Released on '2024-09-02'
### Loading: noEmbryo nodes v1.0.4`

Does that mean I never updated since when I used the update bat file since 2024-09-02???? It would explain the problem (and other problem I have with the new flux models)

**If this is the problem**, I know that I'm not on the ComfyUI github, but can someone have an idea how to fix it without starting from scratch?

Thank you

**Comment by neopiccolorat** [comment]
If anyone comes across this post, I was able to find a working solution for my issue.
Indeed, my ComfyUI was not up to date, and I couldn't update it using a regular Git pull either.

```
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.
```

I found a solution online and decided to try it (I made a backup just in case).

And I used 

`git pull origin master`

It worked for me, and the version of ComfyUI is now up to date.
I was able to use a text-to-video workflow without any errors.
