### ISSUE TITLE
 (IMPORT FAILED) ComfyUI-LTXVideo  

### ISSUE THREAD

**Issue by jonnytracker** [Lightricks/ComfyUI-LTXVideo#33]
installing with latest update of comfyui error
(IMPORT FAILED) [ComfyUI-LTXVideo](https://github.com/Lightricks/ComfyUI-LTXVideo)

**Comment by MoreColors123** [comment]
I tried it all, easynodes still gives me errors. I saw that there is now a new command for installing packages for portable Comfy, but i honestly don't know where to execute it. I tried it inside the customnode folder, the python_embed ... Please help. 

![grafik](https://github.com/user-attachments/assets/1be1546f-43a2-44ab-bd97-c05577360204)

![grafik](https://github.com/user-attachments/assets/7a93fa0f-79d9-4d89-ac41-1f642e1c1762)

**Comment by Vagex** [comment]
Run command with administrator privileges

**Comment by MoreColors123** [comment]
Ok solution is to install via comfy manager. Didn't think of that. Maybe also code was update, I'm not sure. Yesterday it didn't work after trying a lot when just git cloning. 
Now i can play around with the provided workflows finally.

**Comment by auveele** [comment]
Here's your response formatted for GitHub:

I am experiencing the same issue. I installed the module using the Manager, but it doesn't work.

I've tried the following steps:

    Deleted and reinstalled the module.
    Updated all dependencies.
    Manually installed the requirements.txt file.

Despite this, I encounter an error when installing the ltx_video module. Upon starting ComfyUI, I get the following error:

```
Traceback (most recent call last):
  File "D:\_ComfyUI\ComfyUI\nodes.py", line 2027, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\_ComfyUI\ComfyUI\custom_nodes\ComfyUI-LTXVideo\__init__.py", line 3, in <module>
    from .transformer import LTXVModelConfigurator, LTXVShiftSigmas
  File "D:\_ComfyUI\ComfyUI\custom_nodes\ComfyUI-LTXVideo\transformer.py", line 15, in <module>
    from ltx_video.models.transformers.transformer3d import Transformer3DModel
ModuleNotFoundError: No module named 'ltx_video'

Cannot import D:\_ComfyUI\ComfyUI\custom_nodes\ComfyUI-LTXVideo module for custom nodes: No module named 'ltx_video'
```

**Comment by haideraqeeb** [comment]
for me this happened due to the removal of the long-deprecated pkgutil.ImpImporter class, the pip command was not working for python 3.12

i installed python 3.11 and it was working after that

**Comment by StarLabsUA** [comment]
(IMPORT FAILED) [ComfyUI-LTXVideo](https://github.com/Lightricks/ComfyUI-LTXVideo)

how to fix it? :(

**Comment by fullstackwebdev** [comment]
unable to install, same issue.

**Comment by JasonSt0nee** [comment]
me too
Cannot import A:\ComfyUI\custom_nodes\ComfyUI-LTXVideo module for custom nodes: No module named 'ltx_video'

**Comment by sora-1337** [comment]
if nothing works, update your git on your pc.
theres a git version that has a rollbacked LFS handling fix that causes issues when its trying to pull the additional big LFS data from the repo.

**Comment by Dalil260175** [comment]
Here is what solved this problem for me. (on a Mac)
I wasn't able to either  install this node via the manager nor install it via terminal with the "git clone https://github.com/Lightricks/ComfyUI-LTXVideo.git".
When trying to install it via git clone I always got the message that the node was installed successfully but couldn't check out.
So the node wasn't installed completely and wouldn't work.
The issue with the checkout step was due to Git LFS (Large File Storage). This means that the repository I was trying to clone uses Git LFS to manage large files, and my local Git environment didn't Git LFS installed.
The solution (I assume you have Homebrew installed):

Install Git LFS:
brew install git-lfs
Initialize it:
git lfs install

After that I cloned the repository once again (I had to delete the already existing folder comfyui-ltxvideo for it to work) and the clone was complete with all files, so that I could rum pip3 install -r requirements.txt and use this node after that.

**Comment by EmitterLight** [comment]
same error
