### ISSUE TITLE
The imported library version is too old

### ISSUE THREAD

**Issue by coollofty** [Lightricks/ComfyUI-LTXVideo#34]
During installation, there are various version conflicts. If ignore these conflicts, many errors will be reported, the plugin seems impossible to use

**Comment by APCOTech** [comment]
I had the same problem and after I installed LTXVideo, so many custom nodes failed to import. I opened manager and clicked (Try fix) and everything works fine now. I do not think there is a problem about this. CogVideox and PyramidFlow are working fine beside LTXVideo, if this is your concern

**Comment by coollofty** [comment]
I finally installed it, but run it will get this error,  any suggestions?

```
Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-LTXVideo\t5_encoder.py", line 144, in load_model
    return (comfy.sd.CLIP(clip_target),)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\comfy\sd.py", line 90, in __init__
    self.cond_stage_model = clip(**(params))
                            ^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-LTXVideo\t5_encoder.py", line 99, in __init__
    super().__init__(
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-LTXVideo\t5_encoder.py", line 65, in __init__
    T5EncoderModel.from_pretrained(encoder_path, local_files_only=True)
  File "F:\ComfyUI\python_embeded\Lib\site-packages\transformers\modeling_utils.py", line 4097, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\python_embeded\Lib\site-packages\transformers\models\t5\modeling_t5.py", line 1995, in __init__
    self.encoder = T5Stack(encoder_config, self.shared)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\python_embeded\Lib\site-packages\transformers\models\t5\modeling_t5.py", line 889, in __init__
    [T5Block(config, has_relative_attention_bias=bool(i == 0), layer_idx=i) for i in range(config.num_layers)]
  File "F:\ComfyUI\python_embeded\Lib\site-packages\transformers\models\t5\modeling_t5.py", line 889, in <listcomp>
    [T5Block(config, has_relative_attention_bias=bool(i == 0), layer_idx=i) for i in range(config.num_layers)]
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\python_embeded\Lib\site-packages\transformers\models\t5\modeling_t5.py", line 652, in __init__
    T5LayerSelfAttention(config, has_relative_attention_bias=has_relative_attention_bias, layer_idx=layer_idx)
  File "F:\ComfyUI\python_embeded\Lib\site-packages\transformers\models\t5\modeling_t5.py", line 578, in __init__
    self.layer_norm = T5LayerNorm(config.d_model, eps=config.layer_norm_epsilon)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\python_embeded\Lib\site-packages\apex\normalization\fused_layer_norm.py", line 393, in __init__
    fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 676, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 573, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1233, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing fused_layer_norm_cuda:
```
