### ISSUE TITLE
Can't load node: LTXVCLIPModelLoader

### ISSUE THREAD

**Issue by Cey607** [Lightricks/ComfyUI-LTXVideo#36]
I don’t know if it’s because my Comfyui has not been updated. This node prompts an error after download:
```
FETCH DATA from: D:\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[ERROR] An error occurred while retrieving information for the 'LTXVCLIPModelLoader' node.
Traceback (most recent call last):
  File "D:\comfyui\server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "D:\comfyui\server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "D:\ComfyUI\custom_nodes\ComfyUI-LTXVideo\t5_encoder.py", line 123, in INPUT_TYPES
    folder_paths.get_filename_list("text_encoders"),
  File "D:\comfyui\folder_paths.py", line 326, in get_filename_list
    out = get_filename_list_(folder_name)
  File "D:\comfyui\folder_paths.py", line 287, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
KeyError: 'text_encoders'
```
I replaced  `folder_paths.get_filename_list("text_encoders")` with `folder_paths.get_filename_list("clip")` in .\ComfyUI\custom_nodes\ComfyUI-LTXVideo\t5_encoder.py` 
Now problem was solved .
just incase someone meeting same error

**Comment by wangxihao** [comment]
the same error

**Comment by Undi95** [comment]
Update ComfyUI and it fix all the error, not need to modify the file.

**Comment by kshabanaa** [comment]
i updated all things and it game me this error
![Uploading Screenshot 2024-11-25 201102.png…]()

**Comment by balabalalabalaba** [comment]
I also encountered this issue, but I just need to update Comfyui to the latest version

**Comment by JeffreyBull76** [comment]
As @Undi95 said above its to do with the text_encoders folder. I manually created this and updated comfyui and it completely gimped the whole thing. So I had to delete my manually created folder then manually update comfyui using the bat file, and it worked.
