### ISSUE TITLE
LTXV Loader "HeaderTooLarge"

### ISSUE THREAD

**Issue by Vektor369** [Lightricks/ComfyUI-LTXVideo#39]
Any ideas?

```
!!! Exception during processing !!! Error while deserializing header: HeaderTooLarge
Traceback (most recent call last):
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo\loader_node.py", line 50, in load
    weights = safetensors.torch.load_file(ckpt_path, device=str(load_device))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\safetensors\torch.py", line 313, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```

**Comment by AndersEFP** [comment]
You need to redownload the ltx-video-2b-v0.9.safetensors file. Same thing happened to me, check the filesize, it needs to be 9.37GB

**Comment by wbar** [comment]
ypu cloned git clone https://huggingface.co/PixArt-alpha/PixArt-XL-2-1024-MS without `git-lfs` support . install it via `apt install git-lfs` first

**Comment by Vektor369** [comment]
I installed via ComfyUI-Manager as it said it is the "preferred" method.
[https://github.com/Lightricks/ComfyUI-LTXVideo#installation](https://github.com/Lightricks/ComfyUI-LTXVideo#installation)

I was also pretty sure I already had git-lfs, but :shrug:
Either way, I think PixArt downloaded okay because the folder's over 40GB.
Having to go download and install something in order to download and install something else is confusing at best. This is AI. Large file sizes are all we do.

So, I guess it was the ltx-video file then. Not sure how I got one of those and not the other, but there it is.

Thanks.

**Comment by wbar** [comment]
On my side I have forced to use `wget` and download text-encoders files, plus all missing files (based on errors I have started receiving.. and it started working:

```
$ tree /ComfyUI/models/text_encoders/PixArt-XL-2-1024-MS

/ComfyUI/models/text_encoders/PixArt-XL-2-1024-MS/
|-- model_index.json
|-- text_encoder
|   |-- config.json
|   |-- model-00001-of-00002.safetensors
|   |-- model-00002-of-00002.safetensors
|   `-- model.safetensors.index.json
`-- tokenizer
    |-- added_tokens.json
    |-- special_tokens_map.json
    |-- spiece.model
    `-- tokenizer_config.json
```
