### ISSUE TITLE
ModuleNotFoundError: No module named 'easy_nodes'

### ISSUE THREAD

**Issue by flyricci** [Lightricks/ComfyUI-LTXVideo#5]
ModuleNotFoundError: No module named 'easy_nodes',PIP also cannot find 'easy_nodes'

**Comment by StatusReport** [comment]
Make sure to install the requirements (which include `comfyui-easynodes`).

**Comment by MoreColors123** [comment]
yeah i also get errors and the nodes won't load. 
did "pip install comfyui-easynodes" 
but still:

Traceback (most recent call last):
  File "C:\programs\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2026, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\programs\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo\__init__.py", line 1, in <module>
    from .nodes_registry import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\programs\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo\nodes_registry.py", line 4, in <module>
    from easy_nodes import initialize_easy_nodes
ModuleNotFoundError: No module named 'easy_nodes'

**Comment by StatusReport** [comment]
This is probably because you installed the package not into Comfy's virtual environment.

Try the following (up to path mismatch):
```
C:\programs\ComfyUI_windows_portable\python_embedded\python -m pip install comfyui-easynodes
```

This should run pip from the virtual environment of the Python installation that your Comfy is using.

**Comment by krc1983** [comment]
> This is probably because you installed the package not into Comfy's virtual environment.
> 
> Try the following (up to path mismatch):
> 
> ```
> C:\programs\ComfyUI_windows_portable\python_embedded\python -m pip install comfyui-easynodes
> ```
> 
> This should run pip from the virtual environment of the Python installation that your Comfy is using.

I did exactly as you mentioned, still facing the problem...

**Comment by BoosterCore** [comment]
> > This is probably because you installed the package not into Comfy's virtual environment.
> > Try the following (up to path mismatch):
> > ```
> > C:\programs\ComfyUI_windows_portable\python_embedded\python -m pip install comfyui-easynodes
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This should run pip from the virtual environment of the Python installation that your Comfy is using.
> 
> I did exactly as you mentioned, still facing the problem...

same here

**Comment by kvochko** [comment]
@flyricci this should be fixed now, can you please try installing the node again?

**Comment by BoosterCore** [comment]
I tried to reinstall it, but...
```
Traceback (most recent call last):
  File "L:\ComfyUI_New\ComfyUI\nodes.py", line 2027, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "L:\ComfyUI_New\ComfyUI\custom_nodes\ComfyUI-LTXVideo\__init__.py", line 3, in <module>
    from .transformer import LTXVModelConfigurator, LTXVShiftSigmas
  File "L:\ComfyUI_New\ComfyUI\custom_nodes\ComfyUI-LTXVideo\transformer.py", line 15, in <module>
    from ltx_video.models.transformers.transformer3d import Transformer3DModel
ModuleNotFoundError: No module named 'ltx_video'

Cannot import L:\ComfyUI_New\ComfyUI\custom_nodes\ComfyUI-LTXVideo module for custom nodes: No module named 'ltx_video'
```
