### ISSUE TITLE
LTXVCLIPModelLoader Broken

### ISSUE THREAD

**Issue by RamboRogers** [Lightricks/ComfyUI-LTXVideo#51]
<img width="1420" alt="image" src="https://github.com/user-attachments/assets/2a2a24f8-5598-43bb-8caa-f2006e4af141">
I've deployed a fresh environment on a mac and on linux.  I did the git clone.  I get this error no matter what.

ComfyUI was built fresh 2x and all modules are new.  

Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /home/matt/Local/ComfyUI/models/text_encoders/PixArt-XL-2-1024-MS/text_encoder.

2024-12-01T21:07:43.545266 - !!! Exception during processing !!! Incorrect path_or_model_id: '/home/matt/Local/ComfyUI/models/text_encoder'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

I can load models using 
<img width="318" alt="image" src="https://github.com/user-attachments/assets/78510e35-d8fa-44bd-8d5b-4cf6a0ca1217">

**Comment by DaveGravel** [comment]
If i'm not wrong for use this clip you need to use the LTX clip loader.

**Comment by Romanio1997** [comment]
I got the same error. 
<img width="205" alt="sdykYqcF8o" src="https://github.com/user-attachments/assets/5d5a8abd-6c12-4c56-85b4-79fb0f723e82">

**Comment by Neytiri7** [comment]
I got the same error.

**Comment by progmars** [comment]
For me it's a different error:

```
[ERROR] An error occurred while retrieving information for the 'LTXVCLIPModelLoader' node.
Traceback (most recent call last):
  File "D:\Comfy\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "D:\Comfy\ComfyUI\server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy\ComfyUI\custom_nodes\ComfyUI-LTXVideo\t5_encoder.py", line 126, in INPUT_TYPES
    folder_paths.get_filename_list("text_encoders"),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy\ComfyUI\folder_paths.py", line 326, in get_filename_list
    out = get_filename_list_(folder_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy\ComfyUI\folder_paths.py", line 287, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
              ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'text_encoders'

```

My text_encoders folder after git clone looks like this:
![image](https://github.com/user-attachments/assets/c1dd24a0-ac06-4bb7-9fe4-f93c6f598f5b)

**Comment by tstef** [comment]
Hy, I reinstalled, now it gives me this. I reloaded the file model-00001-of-00002, too. Thank you.

<img width="1137" alt="Image" src="https://github.com/user-attachments/assets/64f5fe0b-3784-4066-8125-8de36dce9dd4" />
