### ISSUE TITLE
it always fail to load ltxvideo model

### ISSUE THREAD

**Issue by yli6hz** [Lightricks/ComfyUI-LTXVideo#65]
I try to reinstall and install requirements, but the system still be failed to load this model again. I should give up this model to choose Cogvideo instead.

Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-LTXVideo\__init__.py", line 1, in <module>
    from .loader_node import LTXVLoader  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-LTXVideo\loader_node.py", line 9, in <module>
    from ltx_video.models.autoencoders.causal_video_autoencoder import (
ModuleNotFoundError: No module named 'ltx_video'

Cannot import E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-LTXVideo module for custom nodes: No module named 'ltx_video'
### ComfyUI Version: v0.3.7-11-ga220d11 | Released on '2024-12-09'

It is too hard to install compare with other models.

**Comment by majorsauce** [comment]
For me a pip update and upgrade of setuptools helped:

`pip install --upgrade pip`
`pip install --upgrade setuptools`
