### ISSUE TITLE
using gguf but how to load vae?

### ISSUE THREAD

**Issue by TigerHH6866** [Lightricks/ComfyUI-LTXVideo#66]
WARNING: No VAE weights detected, VAE not initalized.
Requested to load MochiTEModel_
Loading 1 new model
loaded completely 0.0 9083.38671875 True
!!! Exception during processing !!! 'VAE' object has no attribute 'vae_dtype'
Traceback (most recent call last):
  File "/root/autodl-tmp/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/autodl-tmp/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/autodl-tmp/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/root/autodl-tmp/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/root/autodl-tmp/ComfyUI/comfy_extras/nodes_lt.py", line 46, in generate
    t = vae.encode(encode_pixels)
  File "/root/autodl-tmp/ComfyUI/comfy/sd.py", line 407, in encode
    memory_used = self.memory_used_encode(pixel_samples.shape, self.vae_dtype)
AttributeError: 'VAE' object has no attribute 'vae_dtype'

![image](https://github.com/user-attachments/assets/c329346c-e1bd-4976-b681-102899bd3e34)

**Comment by john2stai** [comment]
Use load checkpoint node to load vae
