### ISSUE TITLE
Installation error - Missing Node Types

### ISSUE THREAD

**Issue by mrbhuuu** [Lightricks/ComfyUI-LTXVideo#95]
Hey guys,

I'm having an issue with installing the LTXVidoe in comfyui.
I already went through all the issues raised earlier and tried all the solutions given there. I'm unable to identify what I'm doing wrong here.

Below is my error in the error I'm getting.

![image](https://github.com/user-attachments/assets/ecfa8822-260f-4514-8f56-957c3c5ee889)

## Execute install/(de)activation script for 'C:\Users\user\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo'
 Collecting ltx-video@ git+https://github.com/Lightricks/LTX-Video@ltx-video-0.9.1
   Cloning https://github.com/Lightricks/LTX-Video (to revision ltx-video-0.9.1) to c:\users\user\appdata\local\temp\pip-install-gn_8fu8m\ltx-video_260272d82cf947be9d41106ac08fccda
[!]   Running command git clone --filter=blob:none --quiet https://github.com/Lightricks/LTX-Video 'C:\Users\user\AppData\Local\Temp\pip-install-gn_8fu8m\ltx-video_260272d82cf947be9d41106ac08fccda'
[!]   Running command git checkout -q 4054d5aa9ed7c93a255de60d8625b41087b5c022
   Resolved https://github.com/Lightricks/LTX-Video to commit 4054d5aa9ed7c93a255de60d8625b41087b5c022
   Installing build dependencies: started
   Installing build dependencies: finished with status 'done'
   Getting requirements to build wheel: started
   Getting requirements to build wheel: finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   Getting requirements to build wheel did not run successfully.
[!]   exit code: 1
[!]
[!]   [31 lines of output]
[!]   Traceback (most recent call last):
[!]     File "C:\Users\user\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
[!]       main()
[!]     File "C:\Users\user\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
[!]       json_out['return_val'] = hook(**hook_input['kwargs'])
[!]                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "C:\Users\user\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
[!]       backend = _build_backend()
[!]                 ^^^^^^^^^^^^^^^^
[!]     File "C:\Users\user\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
[!]       obj = import_module(mod_path)
[!]             ^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "importlib\__init__.py", line 90, in import_module
[!]     File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
[!]     File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
[!]     File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
[!]     File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
[!]     File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
[!]     File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
[!]     File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
[!]     File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
[!]     File "<frozen importlib._bootstrap_external>", line 995, in exec_module
[!]     File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
[!]     File "C:\Users\user\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
[!]       import setuptools.version
[!]     File "C:\Users\user\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\version.py", line 1, in <module>
[!]       import pkg_resources
[!]     File "C:\Users\user\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
[!]       register_finder(pkgutil.ImpImporter, find_on_path)
[!]                       ^^^^^^^^^^^^^^^^^^^
[!]   AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: subprocess-exited-with-error
[!]
[!] Getting requirements to build wheel did not run successfully.
[!] exit code: 1
[!]
[!] See above for output.
[!]
[!] note: This error originates from a subprocess, and is likely not a problem with pip.
install/(de)activation script failed: C:\Users\user\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo

**Comment by Ehsanbbaxe** [comment]
same

**Comment by Demwar77** [comment]
It has something to do with Python not being able to load the Pip:  

 AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by Ehsanbbaxe** [comment]
any suggestion?

**Comment by Ehsanbbaxe** [comment]
> Hey guys,
> 
> I'm having an issue with installing the LTXVidoe in comfyui. I already went through all the issues raised earlier and tried all the solutions given there. I'm unable to identify what I'm doing wrong here.
> 
> Below is the error I'm getting.
> 
> ![image](https://private-user-images.githubusercontent.com/122710905/398947769-ecfa8822-260f-4514-8f56-957c3c5ee889.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzOTIwNjMsIm5iZiI6MTczNTM5MTc2MywicGF0aCI6Ii8xMjI3MTA5MDUvMzk4OTQ3NzY5LWVjZmE4ODIyLTI2MGYtNDUxNC04ZjU2LTk1N2MzYzVlZTg4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyOFQxMzE2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTIwYjMwNzI0YzI3NjI0MDMzNWE5N2FkODBiOWRkMTg4NzAwNDUwYmIxZTJmNGQyNjAzZTcwY2M4NTkwNDI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MFkFzJRLDhZjrlkDydFR-Ff53rU4L4I-0RUGC4dqrXg)
> 
> ## ComfyUI-Manager: EXECUTE => ['C:\Users\user\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\python.exe', '-m', 'pip', 'install', 'ltx-video@git+https://github.com/Lightricks/LTX-Video@ltx-video-0.9.1']
> ## Execute install/(de)activation script for 'C:\Users\user\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo'
> Collecting ltx-video@ git+https://github.com/Lightricks/LTX-Video@ltx-video-0.9.1 Cloning https://github.com/Lightricks/LTX-Video (to revision ltx-video-0.9.1) to c:\users\user\appdata\local\temp\pip-install-gn_8fu8m\ltx-video_260272d82cf947be9d41106ac08fccda [!] Running command git clone --filter=blob:none --quiet https://github.com/Lightricks/LTX-Video 'C:\Users\user\AppData\Local\Temp\pip-install-gn_8fu8m\ltx-video_260272d82cf947be9d41106ac08fccda' [!] Running command git checkout -q 4054d5aa9ed7c93a255de60d8625b41087b5c022 Resolved https://github.com/Lightricks/LTX-Video to commit 4054d5aa9ed7c93a255de60d8625b41087b5c022 Installing build dependencies: started Installing build dependencies: finished with status 'done' Getting requirements to build wheel: started Getting requirements to build wheel: finished with status 'error' [!] error: subprocess-exited-with-error [!] [!] Getting requirements to build wheel did not run successfully. [!] exit code: 1 [!] [!] [31 lines of output] [!] Traceback (most recent call last): [!] File "C:\Users\user\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 353, in [!] main() [!] File "C:\Users\user\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 335, in main [!] json_out['return_val'] = hook(**hook_input['kwargs']) [!] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [!] File "C:\Users\user\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 112, in get_requires_for_build_wheel [!] backend = _build_backend() [!] ^^^^^^^^^^^^^^^^ [!] File "C:\Users\user\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 77, in _build_backend [!] obj = import_module(mod_path) [!] ^^^^^^^^^^^^^^^^^^^^^^^ [!] File "importlib__init__.py", line 90, in import_module [!] File "", line 1387, in _gcd_import [!] File "", line 1360, in _find_and_load [!] File "", line 1310, in _find_and_load_unlocked [!] File "", line 488, in _call_with_frames_removed [!] File "", line 1387, in _gcd_import [!] File "", line 1360, in _find_and_load [!] File "", line 1331, in _find_and_load_unlocked [!] File "", line 935, in _load_unlocked [!] File "", line 995, in exec_module [!] File "", line 488, in _call_with_frames_removed [!] File "C:\Users\user\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools__init__.py", line 16, in [!] import setuptools.version [!] File "C:\Users\user\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\version.py", line 1, in [!] import pkg_resources [!] File "C:\Users\user\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pkg_resources__init__.py", line 2191, in [!] register_finder(pkgutil.ImpImporter, find_on_path) [!] ^^^^^^^^^^^^^^^^^^^ [!] AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'? [!] [end of output] [!] [!] note: This error originates from a subprocess, and is likely not a problem with pip. [!] error: subprocess-exited-with-error [!] [!] Getting requirements to build wheel did not run successfully. [!] exit code: 1 [!] [!] See above for output. [!] [!] note: This error originates from a subprocess, and is likely not a problem with pip. install/(de)activation script failed: C:\Users\user\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo

------------------------------------------------------------
RUN THIS INCOMFYUI PORTABLE VERSION:

.\python_embeded\python.exe -m pip install -r .\ComfyUI\custom_nodes\ComfyUI-LTXVideo\requirements.txt

**Comment by Demwar77** [comment]
That does not solve the problem of Python 3.12 not being able to download the files

**Comment by kvochko** [comment]
Hi, it looks like your pip version is older than your python version. Try upgrading pip:

```
> python_embeded\python.exe -m ensurepip --upgrade
```

**Comment by mrbhuuu** [comment]
> 
> RUN THIS INCOMFYUI PORTABLE VERSION:
> 
> .\python_embeded\python.exe -m pip install -r .\ComfyUI\custom_nodes\ComfyUI-LTXVideo\requirements.txt


I did as said above and I got this error.


C:\Users\user\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable>.\python_embeded\python.exe -m pip install -r .\ComfyUI\custom_nodes\ComfyUI-LTXVideo\requirements.txt
Collecting ltx-video@ git+https://github.com/Lightricks/LTX-Video@ltx-video-0.9.1 (from -r .\ComfyUI\custom_nodes\ComfyUI-LTXVideo\requirements.txt (line 2))
  Cloning https://github.com/Lightricks/LTX-Video (to revision ltx-video-0.9.1) to c:\users\user\appdata\local\temp\pip-install-xhx2uruj\ltx-video_3cda9047878a4ae7aface6c87690beec
  Running command git clone --filter=blob:none --quiet https://github.com/Lightricks/LTX-Video 'C:\Users\user\AppData\Local\Temp\pip-install-xhx2uruj\ltx-video_3cda9047878a4ae7aface6c87690beec'
  Running command git checkout -q 4054d5aa9ed7c93a255de60d8625b41087b5c022
  Resolved https://github.com/Lightricks/LTX-Video to commit 4054d5aa9ed7c93a255de60d8625b41087b5c022
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      Traceback (most recent call last):
        File "C:\Users\user\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\user\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\user\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "C:\Users\user\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "importlib\__init__.py", line 90, in import_module
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\user\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\user\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\user\Desktop\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Demwar77** [comment]
> Hi, it looks like your pip version is older than your python version. Try upgrading pip:
> 
> ```
> > .\python_embeded\python.exe -m ensurepip --upgrade
> ```

I get this back: No module named ensurepip

**Comment by vincentw3** [comment]
the same

**Comment by flexiblepackage** [comment]
same error

**Comment by murazi** [comment]
```
python -m ensurepip --upgrade
python.exe:No module named ensurepip
```
![image](https://github.com/user-attachments/assets/6ef35c32-4925-46a2-8a4d-3fe62296de17)

**Comment by Dalil260175** [comment]
Here is what solved this problem for me. (on a Mac)
I wasn't able to either  install this node via the manager nor install it via terminal with the "git clone https://github.com/Lightricks/ComfyUI-LTXVideo.git".
When trying to install it via git clone I always got the message that the node was installed successfully but couldn't check out.
So the node wasn't installed completely and wouldn't work.
The issue with the checkout step was due to Git LFS (Large File Storage). This means that the repository I was trying to clone uses Git LFS to manage large files, and my local Git environment didn't Git LFS installed.
The solution (I assume you have Homebrew installed):

Install Git LFS:
brew install git-lfs
Initialize it:
git lfs install

After that I cloned the repository once again (I had to delete the already existing folder comfyui-ltxvideo for it to work) and the clone was complete with all files, so that I could rum pip3 install -r requirements.txt and use this node after that.

**Comment by EmitterLight** [comment]
same error
