### ISSUE TITLE
'UNetMidBlock3D' object has no attribute 'downsample'

### ISSUE THREAD

**Issue by evaninf** [Lightricks/ComfyUI-LTXVideo#98]
Every workflow with a LTXVModelConfigurator node fails with:

```Traceback (most recent call last):
  File "/mnt/execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/mnt/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/custom_nodes/ComfyUI-LTXVideo/transformer.py", line 164, in configure_sizes
    latent_shape, latent_frame_rate = self.latent_shape_and_frame_rate(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/custom_nodes/ComfyUI-LTXVideo/transformer.py", line 124, in latent_shape_and_frame_rate
    video_scale_factor, vae_scale_factor, _ = get_vae_size_scale_factor(
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/.local/lib/python3.11/site-packages/ltx_video/models/autoencoders/vae_encode.py", line 173, in get_vae_size_scale_factor
    [
  File "/srv/.local/lib/python3.11/site-packages/ltx_video/models/autoencoders/vae_encode.py", line 176, in <listcomp>
    if isinstance(block.downsample, Downsample3D)
                  ^^^^^^^^^^^^^^^^
  File "/srv/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'UNetMidBlock3D' object has no attribute 'downsample'
```

I've tried LTXV 0.9, 0.9.1, GGUF variants, every standalone VAE I have found, extracting the VAE from official safetensors, nothing works.

**Comment by wencxxxxxx** [comment]
+1
